"""Add daily_target to User

Revision ID: 28e6586baa3a
Revises: fb00e72ab086
Create Date: 2025-07-06 07:22:44.553196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28e6586baa3a'
down_revision: Union[str, Sequence[str], None] = 'fb00e72ab086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('daily_target', sa.Integer(), nullable=False, server_default="5"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'daily_target')
    # ### end Alembic commands ###
